### PR TITLE
Deprecate `scope` in favor of `before_scope` and `after_scope`

### LINKED ISSUE #35: Support Relay connections
Right now when I use the `connection` method to define a Relay connection with GraphQL, the `scope` method doesn't work properly. It is initialised with the current_user and the current type, not the scope.

Is this to be expected? I was expecting the resolve function of my scope to be passed my ActiveRecord::Relation or Mongoid::Criteria.

### PR DESCRIPTION
**Pull request by phyrog**
Closes #35. This adds `before_scope` and `after_scope` and deprecates `scope`.

`before_scope` is run before `resolve` and receives the parent object as first argument, while `after_scope` is run after `resolve` and receives the output of `resolve` as first argument.

### CODE REVIEW

File: lib/graphql-pundit/instrumenters/after_scope.rb [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+
+require 'pundit'
+require_relative 'scope'
+
+module GraphQL
+  module Pundit
+    module Instrumenters
+      # Instrumenter that supplies `after_scope`
+      class AfterScope < Scope
+
```
Comment (eugenk) [inline lib/graphql-pundit/instrumenters/after_scope.rb]: Empty line at beginning of the class. Why doesn't rubocop complain?

File: lib/graphql-pundit/instrumenters/before_scope.rb [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+
+require 'pundit'
+require_relative 'scope'
+
+module GraphQL
+  module Pundit
+    module Instrumenters
+      # Instrumenter that supplies `before_scope`
+      class BeforeScope < Scope
+
```
Comment (eugenk) [inline lib/graphql-pundit/instrumenters/before_scope.rb]: Same empty line here.

File: spec/graphql-pundit/instrumenters/after_scope_spec.rb [hunk 3]
```diff
@@ -0,0 +1,240 @@
...
+      let(:field) do
+        GraphQL::Field.define(type: '[Post!]') do
+          name :unpublished_posts
+          property :posts
+          after_scope ->(posts, _args, _ctx) { posts.select { |p| !p.published } }
+        end
+      end
+
+      it 'filters the list' do
+        expect(result.map { |post| post.published }).to match_array([false])
```
Comment (eugenk) [inline spec/graphql-pundit/instrumenters/after_scope_spec.rb]: Style: `map(&:published)`

File: spec/graphql-pundit/instrumenters/after_scope_spec.rb [hunk 4]
```diff
@@ -0,0 +1,240 @@
...
+      let(:field) do
+        GraphQL::Field.define(type: '[Post!]') do
+          name :published_posts
+          property :posts
+          after_scope PostPolicy
+        end
+      end
+
+      it 'filters the list' do
+        expect(result.map { |post| post.published }).to match_array([true])
```
Comment (eugenk) [inline spec/graphql-pundit/instrumenters/after_scope_spec.rb]: Style: `map(&:published)`
